import Foundation

/// Looks up a UI string in Resources/<lang>.lproj/Localizable.strings (generated by make-resources.py).
func L(_ key: String) -> String { NSLocalizedString(key, comment: "") }

/// Localized string with format arguments (%@, %d, positional %1$d ...).
func L(_ key: String, _ arguments: CVarArg...) -> String {
    String(format: L(key), locale: Locale.current, arguments: arguments)
}

/// Bundled Help.txt for the current language (HelpDocument markup: ## / ### headings, - bullets).
func helpText() -> String {
    if let url = Bundle.main.url(forResource: "Help", withExtension: "txt"),
       let text = try? String(contentsOf: url, encoding: .utf8) {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        if !trimmed.isEmpty { return trimmed }
    }
    return "Help is not available. Reinstall the app."
}
