import AppKit

// Help text is bundled per language (B16) and readable offline.
final class LocalHelp: NSObject {
    static let shared = LocalHelp()
    private var window: NSWindow?
    static let title = "MightyEdit"
    /// Localized help from Resources/<lang>.lproj/Help.txt (generated by make-resources.py).
    static var content: String {
        guard let url = Bundle.main.url(forResource: "Help", withExtension: "txt"),
              let text = try? String(contentsOf: url, encoding: .utf8) else { return L("help.missing") }
        return text
    }
    func install() {
        let main = NSApp.mainMenu ?? NSMenu()
        let help = NSApp.helpMenu ?? NSMenu(title: L("help"))
        if !main.items.contains(where: { $0.submenu === help }) {
            let root = NSMenuItem(); root.submenu = help; main.addItem(root)
        }
        if !help.items.contains(where: { $0.target === self }) {
            let item = help.addItem(withTitle: L("menu.help"), action: #selector(show), keyEquivalent: "?")
            item.target = self
        }
        MainActor.assumeIsolated { HelpLinks.addNoteItem(to: help) }
        NSApp.mainMenu = main
        NSApp.helpMenu = help
    }
    @objc func show() {
        // Rendered by the shared HelpDocument (## sections, ### subsections, - bullets, 1. steps, **bold**).
        if window == nil { window = MainActor.assumeIsolated { HelpDocument.makeWindow(windowTitle: L("menu.help"), text: Self.content, heading: Self.title) } }
        NSApp.activate(ignoringOtherApps: true); window?.makeKeyAndOrderFront(nil)
    }
}
